### ISSUE TITLE
Crear el modelo de receta (Recipe)

### ISSUE THREAD

**Issue by MeLlamoPablo** [adaits-2daw-cliente-grupo1/ejercicio-1#1]
Una receta debe tener:

* id
* nombre
* ingredientes (mínimo 3)
   * El objeto de ingrediente debe ser un array de objetos con dos propiedades: ingrediente (Ingredient) y cantidad (string)
* pasos (mínimo 5)
* tipo de comida
* origen
* id del autor

**Comment by Juanlu1995** [comment]
El error que te comentaba @MeLlamoPablo  


git status
En la rama recipe
nothing to commit, working directory clean
➜  Ejercicio1-Clientes git:(recipe) git push --set-upstream origin recipe 
Username for 'https://github.com': juanlu_21@hotmail.com	
Password for 'https://juanlu_21@hotmail.com@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/adaits-2daw-cliente-grupo1/ejercicio-1/'

**Comment by Juanlu1995** [comment]
@MeLlamoPablo  el error que te comentaba:


fatal: Authentication failed for 'https://github.com/adaits-2daw-cliente-grupo1/ejercicio-1/'

**Comment by Juanlu1995** [comment]
contraseña y password mias correctas

**Comment by MeLlamoPablo** [comment]
Buenos días, creo que tienes que poner tu nombre de usuario de github para hacer push, no tu correo.

Si no te funciona, también puedes hacer push mediante ssh. Es más coñazo de configurar pero es más cómodo de usar después.

**Comment by Juanlu1995** [comment]
Por mi parte esto ya está hecho, solo tengo un par de cosillas que quiero comentarte en clase @MeLlamoPablo. Las pruebas no puedo hacerlas ya que necesito implementar ingredientes que se está encargando @Artiaga2

**Comment by MeLlamoPablo** [comment]
Ok gracias @Juanlu1995. Cuando puedas lanza un pull request a master y reviso el código.

Aquí tienes una guía: https://help.github.com/articles/creating-a-pull-request/

Si pones en la descripción del pull request `Closes #1` esta issue se cerrará automáticamente cuando se haga el merge.
