### ISSUE TITLE
Modificar el atributo ingredients de Recipe

### ISSUE THREAD

**Issue by MeLlamoPablo** [adaits-2daw-cliente-grupo1/ejercicio-1#10]
Como expliqué en #1, `ingredients` tiene que ser un array de objetos, no un array de ingredientes. Esto lo he pasado por alto al hacer la review de #5.

Cada ingrediente debe ser un objeto que contenga "ingredient" y "quantity". Es decir, sería algo así:

```js
const ingredients = [
    {
        ingredient: new Ingredient(/* ... */),
        quantity: "300 g"
    },
    /* ... */
]
```

Por lo tanto, el constructor debe controlar que la propiedad `ingredient` sea `Ingredient` y la propiedad `quantity` sea `string`, y que ambas estén presentes.

**Comment by Juanlu1995** [comment]
abría que cerrarla, no?

**Comment by MeLlamoPablo** [comment]
Habría*
