### ISSUE TITLE
Crear función 1.1 - getRecipesByNameOrSteps

### ISSUE THREAD

**Issue by MeLlamoPablo** [adaits-2daw-cliente-grupo1/ejercicio-1#14]
### Enunciado: 

```
Función que deberá devolver todas las recetas que tengan en su nombre o en la lista
de pasos, la cadena pasada al método.
```

### Tarea:

Crear un archivo `getRecipesByNameOrSteps.js` que implementa la función, y un archivo `getRecipesByNameOrSteps.spec.js` que realiza las pruebas de la función. Estos archvios deberán ir dentro de las carpetas `pages/search`.

**Comment by Juanlu1995** [comment]
ésta también deberíamos cerrarla, no?
