### ISSUE TITLE
Crear funciones para persistir el estado

### ISSUE THREAD

**Issue by MeLlamoPablo** [adaits-2daw-cliente-grupo1/ejercicio-1#21]
### Objetivos

El objetivo de esta issue es crear un archivo `storage.js` que se encargue de persistir la información al navegador, y se encargue de cargarla al iniciar la página. Para persistir la información usaremos [localStorage](https://developer.mozilla.org/es/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). Para convertir el estado a string (todo lo que vaya a localStorage debe ser string) usaremos [JSON.stringify](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/JSON/stringify), y para recuperar los datos usaremos [JSON.parse](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/JSON/parse).

### Especificación

El archivo `storage.js` debe exportar tres funciones.

* `saveStateToStorage`. No recibe ni devuelve datos. Debe guardar el estado tal cual viene de `getState()` en el `localStorage`.
* `loadStateFromStorage`. No recibe parámetros ni devuelve datos. Debe cargar el estado de `localStorage` y colocarlo en el estado de la aplicación usando `replaceWholeState()`. Debe controlar que el usuario no haya entrado nunca en la web, o haya borrado los datos del navegador.
* `saveInitialStateToStorage`. Guarda un estado con recetas, valoraciones y usuarios predefinidos en el `localStorage`. Esta función debe llamarse cuando no existe el estado dentro del `localStorage`, para crear los datos iniciales.

Asimismo se debe modificar el archivo `index.js` para que haga lo siguiente:

* Al cargar la página, comprobar si el usuario tiene un estado guardado en el storage.
    * Si lo tiene, lo cargamos, para que el usuario pueda continuar con los datos de su última sesión.
    * Si no lo tiene, creamos uno por defecto.

**Comment by Juanlu1995** [comment]
Lo voy a intentar. No me la asigno por que son demasiadas cosas nuevas, tengo que hacer más cosas y no sé si sabré jajajaja

**Comment by Juanlu1995** [comment]
Pablo, no he entendido esto
`loadStateFromStorage. No recibe parámetros ni devuelve datos. Debe cargar el estado de localStorage y colocarlo en el estado de la aplicación usando replaceWholeState(). Debe controlar que el usuario no haya entrado nunca en la web, o haya borrado los datos del navegador.`
qué y cómo es eso?

**Comment by MeLlamoPablo** [comment]
Te has leído la documentación? En el localStorage puedes meter strings que se guardan en el navegador. `loadStateFromStorage` deberá comprobar si esa string existe, y en caso afirmativo, parsearla y meterla en el estado con la función `replaceWholeState` de `appState.js`

¿Qué no entiendes exactamente?
