### ISSUE TITLE
Crear función 2.2 - addOrEditStepInRecipe

### ISSUE THREAD

**Issue by MeLlamoPablo** [adaits-2daw-cliente-grupo1/ejercicio-1#23]
### Enunciado: 

```
Función que deberá incluir o remplazar un paso en una receta. Y devolverá la receta
actualizada.
```

### Tarea:

Crear un archivo `addOrEditStepInRecipe.js` que implementa la función, y un archivo `addOrEditStepInRecipe.spec.js` que realiza las pruebas de la función. Estos archvios deberán ir dentro de las carpetas `pages/edit`.

### Notas:

Esta función recibirá tres parámetros: `recipe`, la receta sobre la cual queremos realizar la modificación, `newStep`, el contenido del nuevo paso, y `existingStepIndex`, opcional, el índice en el array de pasos del paso que queremos modificar. Si no se pasa, se añade el paso al final del array.

Si no hay ningún error, la función deberá actualizar la receta en el estado.

**Comment by Juanlu1995** [comment]
dado que la receta no se puede modificar al ser un parámetro (no-param-reassingn), doy por echo que la llamada a la funcion será para devolver una receta modificada para igualarla a la que existe, no?

`recetaParaModificar = addOrEditIngredientInRecipe(recetaParaMOdificarInRecipe,newStep,existingStepIndex);`

Es así o hay algo que se me pasa?

@MeLlamoPablo

**Comment by MeLlamoPablo** [comment]
Efectivamente. En un programa tradicional la función sería así (pseudocódigo):

```
function modificarNombreReceta(recetaAntigua, nuevoNombre) {
    recetaAntigua.nombre = nuevoNombre
    return recetaAntigua
}
```

En un programa que aplica la inmutabilidad, sería así:

```
function modificarNombreReceta(recetaAntigua, nuevoNombre) {
    nuevaReceta = copia de recetaAntigua
    nuevaReceta.nombre = nuevoNombre
    return nuevaReceta
}
```

De esta forma nunca tocamos `recetaAuntigua`.

**Comment by MeLlamoPablo** [comment]
Cerrado en #37
