### ISSUE TITLE
Crear función 2.3 - addOrEditIngredientInRecipe

### ISSUE THREAD

**Issue by MeLlamoPablo** [adaits-2daw-cliente-grupo1/ejercicio-1#24]
### Enunciado: 

```
Función que deberá incluir o remplazar un ingrediente en una receta. Y devolverá la
receta actualizada. Si el ingrediente ya está, deberá actualizarse, sino deberá incluirse.
```

### Tarea:

Crear un archivo `addOrEditIngredientInRecipe.js` que implementa la función, y un archivo `addOrEditIngredientInRecipe.spec.js` que realiza las pruebas de la función. Estos archvios deberán ir dentro de las carpetas `pages/edit`.

### Notas:

Esta función recibirá los mismos parámetros que  #23, pero con `Ingredient` en vez de una string, por lo tanto tendrá que comprobar que el parámetro sea de verdad un `Ingredient`.

Si no hay ningún error, la función deberá actualizar la receta en el estado.

**Comment by Juanlu1995** [comment]
aquí hay un vacío: el ingrediente tiene que ir acompañado por una cantidad, que tambien tandría que ser pasada por parámetro, almenos cuando el ingrediente es nuevo

**Comment by Juanlu1995** [comment]
@MeLlamoPablo tú que opinas "Boss"?  jajaja

**Comment by MeLlamoPablo** [comment]
Toda la razón @Juanlu1995!

En este caso el parámetro no sería el ingrediente en sí, sino el objeto con `ingredient` y `quantity`.
